services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - dbnet

  user_balance:
    build: .
    image: user_balance
    container_name: user_balance
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./user_balance:/app/www/user_balance
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data: